namespace Technorix.JobManagement_3.Model
{
    public class Job
    {
        public int Id { get; set; } // This should be auto-generated by the database
        public string Code { get; set; } // Might be auto-generated
        public string Title { get; set; } // Required
        public string Description { get; set; } // Required
        public int LocationId { get; set; } // Required
        public Location Location { get; set; } // Navigation property
        public int DepartmentId { get; set; } // Required
        public Department Department { get; set; } // Navigation property
        public DateTime PostedDate { get; set; } // Required, auto-set by the server
        public DateTime ClosingDate { get; set; } // Required
    }
}

